name: Build and Deploy To Dev

on: 
  workflow_dispatch:
    inputs:
      branch:
        type: string
        

jobs:
    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Build    
      run: | 
        cd api
        npm i
        npm run clean
        npm run build 


  
                
          
     
    
             
 

    
