name: Build and Deploy To Dev

on: 
  workflow_dispatch:
    inputs:
      branch:
        type: string
        

jobs:
  Create_infrastructure:
    name: Create_infrastructure
    runs-on: ubuntu-latest
    steps: 
    - name: Code checkout    
      uses: actions/checkout@v3
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: create resources
      run: |
       cd api
       az group create --name rg-appservice-codepush-server-dev --location centralus
       az deployment group create --resource-group rg-appservice-codepush-server-dev --template-file codepush-infrastructure.bicep --parameters '{ \"location\": { \"value\": \"centralus\" }}'  
    # - name: Setup Node 
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: '16.x'
    # - name: Build    
    #   run: | 
    #     npm i
    #     npm run build
    # - name: Deploy Code to infrastructure   
    #   run : | 
    #    az webapp deploy --resource-group rg-appservice-mobile-code --name ftr-mobile-code --src-path ./api 


    

  
                
          
     
    
             
 

    
